/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.tsx',
        './resources/**/*.jsx',
        './resources/**/*.js',
        './resources/**/*.ts',
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'primary':                    '#0053cc',
                'primary-dim':                '#0048b3',
                'primary-fixed':              '#779dff',
                'primary-fixed-dim':          '#608fff',
                'primary-container':          '#dce8ff',
                'on-primary':                 '#ffffff',
                'on-primary-container':       '#001f56',
                'inverse-primary':            '#5b8cff',
                'secondary':                  '#006853',
                'secondary-dim':              '#005b48',
                'secondary-container':        '#6dfad2',
                'on-secondary':               '#003829',
                'on-secondary-container':     '#005d4a',
                'tertiary':                   '#8b4b00',
                'tertiary-container':         '#f99a3f',
                'on-tertiary':                '#fff0e6',
                'on-tertiary-container':      '#4d2700',
                'surface':                    '#f8f5ff',
                'surface-bright':             '#f8f5ff',
                'surface-dim':                '#cdd1ff',
                'surface-variant':            '#d8daff',
                'surface-container-lowest':   '#ffffff',
                'surface-container-low':      '#f0efff',
                'surface-container':          '#e6e6ff',
                'surface-container-high':     '#dfe0ff',
                'surface-container-highest':  '#d8daff',
                'on-surface':                 '#272c51',
                'on-surface-variant':         '#545981',
                'outline':                    '#6f749e',
                'outline-variant':            '#a6aad7',
                'error':                      '#b31b25',
                'error-container':            '#ffdad6',
                'on-error':                   '#ffffff',
                'on-error-container':         '#410002',
            },
            fontFamily: {
                sans:     ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};