/** @type {import('tailwindcss').Config} */
import defaultTheme from 'tailwindcss/defaultTheme';
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.tsx',
        './resources/**/*.jsx',
        './resources/**/*.js',
        './resources/**/*.ts',
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
    ],
    theme: {
        extend: {
            colors: {
                'primary':                    '#149B9B',
                'primary-dim':                '#0f8080',
                'primary-fixed':              '#5ec9c9',
                'primary-fixed-dim':          '#3dbdbd',
                'primary-container':          '#E0F2F2',
                'on-primary':                 '#ffffff',
                'on-primary-container':       '#002020',
                'inverse-primary':            '#7dd4d4',
                'secondary':                  '#26A69A',
                'secondary-dim':              '#1e8c81',
                'secondary-container':        '#B2DFDB',
                'on-secondary':               '#ffffff',
                'on-secondary-container':     '#004D40',
                'tertiary':                   '#8b4b00',
                'tertiary-container':         '#f99a3f',
                'on-tertiary':                '#ffffff',
                'on-tertiary-container':      '#4d2700',
                'surface':                    '#F8FEFE',
                'surface-bright':             '#F0F7F7',
                'surface-dim':                '#c8dada',
                'surface-variant':            '#d4e8e8',
                'surface-container-lowest':   '#ffffff',
                'surface-container-low':      '#f0f7f7',
                'surface-container':          '#e4f0f0',
                'surface-container-high':     '#d8eaea',
                'surface-container-highest':  '#cde4e4',
                'on-surface':                 '#1A1C1C',
                'on-surface-variant':         '#3F4948',
                'outline':                    '#6F7978',
                'outline-variant':            '#BFC9C8',
                'error':                      '#BA1A1A',
                'error-container':            '#ffdad6',
                'on-error':                   '#ffffff',
                'on-error-container':         '#410002',
            },
            fontFamily: {
                sans:     ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};